import assert from "node:assert/strict";
import { POKEMON_ASSET_IDS, POKEMON_NAME_TRANSLATIONS, pokemonAssetId, pokemonAssetKey } from "../web/pokemon_names.js";

assert.equal(POKEMON_ASSET_IDS.katapuldra, "dragapult");
assert.equal(POKEMON_ASSET_IDS.uhafnir, "noivern");
assert.equal(POKEMON_ASSET_IDS.pantimos, "mrmime");
assert.equal(POKEMON_ASSET_IDS.nidoranf, "nidoranf");
assert.equal(POKEMON_ASSET_IDS.flabebe, "flabebe");
assert.ok(POKEMON_NAME_TRANSLATIONS.length >= 1000);
assert.ok(Object.keys(POKEMON_ASSET_IDS).length >= POKEMON_NAME_TRANSLATIONS.length);

assert.equal(pokemonAssetKey("Nidoran♀"), "nidoranf");
assert.equal(pokemonAssetKey("Nidoran♂"), "nidoranm");
assert.equal(pokemonAssetId("UHaFniR"), "noivern");
assert.equal(pokemonAssetId("Katapuldra"), "dragapult");
assert.equal(pokemonAssetId("Kapu-Kime"), "tapufini");
assert.equal(pokemonAssetId("Arceus"), "arceus");
assert.equal(pokemonAssetId("Giratina"), "giratina");
assert.equal(pokemonAssetId("Lusardin"), "wishiwashi");

assert.equal(pokemonAssetId("Ogerpon-Gestein"), "ogerponcornerstone");
assert.equal(pokemonAssetId("Ogerpon-Wasser"), "ogerponwellspring");
assert.equal(pokemonAssetId("Demeteros-T"), "landorustherian");
assert.equal(pokemonAssetId("Demeteros-Therian"), "landorustherian");
assert.equal(pokemonAssetId("Demeteros-Tiergeistform"), "landorustherian");
assert.equal(pokemonAssetId("Demeteros-I"), "landorus");
assert.equal(pokemonAssetId("Demeteros-Inkarnationsform"), "landorus");
assert.equal(pokemonAssetId("Mega-Despotar"), "tyranitarmega");
assert.equal(pokemonAssetId("Rotom (Hitze-Form)"), "rotomheat");
assert.equal(pokemonAssetId("Rotom-Hitze"), "rotomheat");
assert.equal(pokemonAssetId("Rotom-H"), "rotomheat");
assert.equal(pokemonAssetId("Rotom-Schneide"), "rotommow");
assert.equal(pokemonAssetId("Rotom (Schneide-Form)"), "rotommow");
assert.equal(pokemonAssetId("Rotom-W"), "rotomwash");
assert.equal(pokemonAssetId("Boreos-Tiergeistform"), "tornadustherian");
assert.equal(pokemonAssetId("Boreos-T"), "tornadustherian");
assert.equal(pokemonAssetId("Boreos-I"), "tornadus");
assert.equal(pokemonAssetId("Deoxys-Geschwindigkeit"), "deoxysspeed");
assert.equal(pokemonAssetId("hoopa entfesseltes hoopa"), "hoopaunbound");
assert.equal(pokemonAssetId("Hoopa-Entfesselt"), "hoopaunbound");
assert.equal(pokemonAssetId("Cupidos-Therian"), "enamorustherian");
assert.equal(pokemonAssetId("Keldeo"), "keldeo");
assert.equal(pokemonAssetId("Amigento-Normal"), "silvally");
assert.equal(pokemonAssetId("Flampivian"), "darmanitan");
assert.equal(pokemonAssetId("Giga-Patinaraja"), "copperajahgmax");
assert.equal(pokemonAssetId("Giga-Machomei"), "machampgmax");
assert.equal(pokemonAssetId("Giga-Drapfel"), "flapplegmax");
assert.equal(pokemonAssetId("Giga-Deponitox"), "garbodorgmax");
assert.equal(pokemonAssetId("Giga-Schlapfel"), "appletungmax");
assert.equal(pokemonAssetId("Giga-Maritellit"), "orbeetlegmax");
assert.equal(pokemonAssetId("Riffex-Hoch"), "toxtricity");
assert.equal(pokemonAssetId("Wolwerock-Dämmerungsform"), "lycanrocdusk");
assert.equal(pokemonAssetId("Wolwerock-Tag"), "lycanroc");
assert.equal(pokemonAssetId("Wolwerock-Tagform"), "lycanroc");
assert.equal(pokemonAssetId("Meistergrif"), "conkeldurr");
assert.equal(pokemonAssetId("Drifzepli"), "drifblim");
assert.equal(pokemonAssetId("Zygarde-50%"), "zygarde");
assert.equal(pokemonAssetId("Psiaugon (männlich)"), "meowstic");
assert.equal(pokemonAssetId("Schwallbos"), "swellow");
assert.equal(pokemonAssetId("Shnurgast"), "purugly");
assert.equal(pokemonAssetId("Servol-w"), "indeedeef");
