import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const indexHtml = readFileSync(new URL("../web/index.html", import.meta.url), "utf8");
const appJs = readFileSync(new URL("../web/app.js", import.meta.url), "utf8");
const stylesCss = readFileSync(new URL("../web/styles.css", import.meta.url), "utf8");
const dataModeSelect = indexHtml.match(/<select id="data-mode-filter">[\s\S]*?<\/select>/)?.[0] ?? "";
const columnProfileSelect = indexHtml.match(/<select id="column-profile-filter">[\s\S]*?<\/select>/)?.[0] ?? "";

assert.equal(indexHtml.includes('id="summary-grid"'), false);
assert.equal(appJs.includes("renderSummary("), false);
assert.equal(indexHtml.includes('id="data-mode-filter"'), true);
assert.equal(indexHtml.includes('class="primary-tabs"'), true);
assert.equal(indexHtml.includes('class="tabs sub-tabs"'), true);
assert.equal(indexHtml.includes('id="column-profile-filter"'), true);
assert.equal(indexHtml.includes('data-view-group="overview"'), false);
assert.equal(indexHtml.includes('data-view-group="people"'), true);
assert.equal(indexHtml.includes('data-view-group="pokemon"'), true);
assert.equal(indexHtml.includes('data-view-group="seasons"'), true);
assert.equal(indexHtml.includes('data-view-group="data"'), true);
assert.equal(indexHtml.includes('data-view="person-details"'), false);
assert.equal(indexHtml.includes('data-view="pokemon-detail"'), false);
assert.equal(indexHtml.includes('id="battle-history-table"'), false);
assert.equal(indexHtml.includes('id="bracket-overview"'), true);
assert.equal(indexHtml.includes('id="person-summary-section"'), false);
assert.equal(indexHtml.includes('id="pokemon-summary-section"'), false);
assert.equal(indexHtml.includes('id="person-summary-table"'), false);
assert.equal(indexHtml.includes('id="pokemon-summary-table"'), false);
assert.equal(indexHtml.includes('<summary'), true);
assert.equal(stylesCss.includes(".person-focus[hidden]"), true);
assert.equal(stylesCss.includes(".pokemon-focus[hidden]"), true);
assert.equal(stylesCss.includes(".detail-table-section"), true);
assert.equal(stylesCss.includes(".bracket-board"), true);
assert.equal(stylesCss.includes(".pokemon-sprite-animated"), true);
assert.equal(appJs.includes("setDetailSections("), true);
assert.equal(appJs.includes("renderBracketOverview("), true);
assert.equal(appJs.includes('getPokemon?.(id, { gen: "ani" })'), true);
assert.equal(appJs.includes("pokemon-sprite-animated"), true);
assert.equal(appJs.includes("${fallback}<img"), false);
assert.equal(appJs.includes("renderTable(\"#battle-history-table\""), false);
assert.equal(appJs.includes('renderTable("#person-summary-table"'), false);
assert.equal(appJs.includes('renderTable("#pokemon-summary-table"'), false);
assert.equal(appJs.includes('navigateToView("all-time")'), true);
assert.match(appJs, /data-clear-person-focus[\s\S]*?navigateToView\("all-time"\)/);
assert.match(appJs, /data-clear-pokemon-focus[\s\S]*?navigateToView\("all-time"\)/);
assert.equal(appJs.includes("data-matchup-select"), true);
assert.equal(appJs.includes("selectMatchupParticipant("), true);
assert.match(appJs, /matchup:\s*\["matchVideos"\]/);
assert.match(appJs, /const matchColumns = columnsForProfile\(\["season", "division", "week", "player_a", "player_b", "score", "winner", "videos", "source"\]/);
assert.match(appJs, /videos:\s*videoLinksForMatch\(row\.match_id\)/);
assert.match(appJs, /tableHtml\(matchRows, matchColumns, \["player_a", "player_b", "videos", "source"\]\)/);
assert.equal(appJs.includes("personOptionsFromAllTimeRows("), true);
const matchupOptionsBlock = appJs.match(/function matchupOptions\(\) \{[\s\S]*?\n\}/)?.[0] ?? "";
assert.match(matchupOptionsBlock, /filteredPersonStats/);
assert.equal(matchupOptionsBlock.includes("team_a"), false);
assert.equal(matchupOptionsBlock.includes("team_name"), false);
assert.match(appJs, /seasonFilter\.addEventListener\("change"[\s\S]*?populateMatchupOptions\(\)/);
assert.match(appJs, /divisionFilter\.addEventListener\("change"[\s\S]*?populateMatchupOptions\(\)/);
assert.match(appJs, /searchFilter\.addEventListener\("input"[\s\S]*?populateMatchupOptions\(\)/);
assert.equal(dataModeSelect.includes('value="primary"'), true);
assert.equal(dataModeSelect.includes('value="league2"'), true);
assert.equal(dataModeSelect.includes('value="league1"'), false);
assert.equal(dataModeSelect.includes('value="all"'), false);
assert.equal(columnProfileSelect.includes('value="compact"'), true);
assert.equal(columnProfileSelect.includes('value="performance"'), true);
assert.equal(columnProfileSelect.includes('value="history"'), true);
assert.equal(columnProfileSelect.includes('value="sources"'), true);
assert.equal(columnProfileSelect.includes('value="full"'), true);
assert.equal(appJs.includes('readPreference("gpl-column-profile", "full")'), true);
assert.equal(appJs.includes("applyDataMode("), true);
assert.equal(appJs.includes("columnsForProfile("), true);
assert.match(appJs, /numberValue\(b\.rating\)[\s\S]*?numberValue\(b\.elo\)/);
