import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const indexHtml = readFileSync(new URL("../web/index.html", import.meta.url), "utf8");
const appJs = readFileSync(new URL("../web/app.js", import.meta.url), "utf8");
const stylesCss = readFileSync(new URL("../web/styles.css", import.meta.url), "utf8");
const manualKilllistHtml = readFileSync(new URL("../web/manual-killlist-entry.html", import.meta.url), "utf8");
const manualKilllistJs = readFileSync(new URL("../web/manual_killlist_entry.js", import.meta.url), "utf8");
const teamGraphicsHtml = readFileSync(new URL("../web/team-graphics-entry.html", import.meta.url), "utf8");
const teamGraphicsJs = readFileSync(new URL("../web/team_graphics_entry.js", import.meta.url), "utf8");
const dataModeSelect = indexHtml.match(/<select id="data-mode-filter">[\s\S]*?<\/select>/)?.[0] ?? "";
const columnProfileSelect = indexHtml.match(/<select id="column-profile-filter">[\s\S]*?<\/select>/)?.[0] ?? "";

assert.equal(indexHtml.includes('id="summary-grid"'), false);
assert.equal(appJs.includes("renderSummary("), false);
assert.equal(indexHtml.includes('id="data-mode-filter"'), true);
assert.equal(indexHtml.includes('class="primary-tabs"'), true);
assert.equal(indexHtml.includes('class="tabs sub-tabs"'), true);
assert.equal(indexHtml.includes('id="column-profile-filter"'), true);
assert.equal(indexHtml.includes('class="score-explainer"'), true);
assert.equal(indexHtml.includes('class="score-explainer" open'), false);
assert.equal(indexHtml.includes('class="summary-grid person-summary-grid"'), true);
assert.equal(indexHtml.includes('id="view-roster-detail"'), true);
assert.equal(indexHtml.includes('id="roster-detail-visual"'), true);
assert.equal(indexHtml.includes('data-view-group="overview"'), false);
assert.equal(indexHtml.includes('data-view-group="people"'), true);
assert.equal(indexHtml.includes('data-view-group="pokemon"'), true);
assert.equal(indexHtml.includes('data-view-group="seasons"'), true);
assert.equal(indexHtml.includes('data-view-group="data"'), true);
assert.equal(indexHtml.includes('data-view="person-details"'), false);
assert.equal(indexHtml.includes('data-view="pokemon-detail"'), false);
assert.equal(indexHtml.includes("PokÃ©mon"), false);
assert.equal(indexHtml.includes("KÃ¤mpfe"), false);
assert.equal(indexHtml.includes("Pokémon"), true);
assert.equal(indexHtml.includes("Kämpfe"), true);
assert.doesNotMatch([manualKilllistHtml, manualKilllistJs, teamGraphicsHtml, teamGraphicsJs].join("\n"), /fuer|loeschen|Zurueck/);
assert.match(manualKilllistHtml, /für Trainer-Zuordnungen/);
assert.match(manualKilllistHtml, /Lokale Auswahl löschen/);
assert.match(teamGraphicsHtml, /Lokale Auswahl löschen/);
assert.equal(indexHtml.includes('id="battle-history-table"'), false);
assert.equal(indexHtml.includes('id="bracket-overview"'), true);
assert.equal(indexHtml.includes('id="person-summary-section"'), false);
assert.equal(indexHtml.includes('id="pokemon-summary-section"'), false);
assert.equal(indexHtml.includes('id="person-summary-table"'), false);
assert.equal(indexHtml.includes('id="pokemon-summary-table"'), false);
assert.equal(indexHtml.includes('<summary'), true);
assert.equal(stylesCss.includes(".person-focus[hidden]"), true);
assert.equal(stylesCss.includes(".pokemon-focus[hidden]"), true);
assert.equal(stylesCss.includes(".detail-table-section"), true);
assert.equal(stylesCss.includes(".score-explainer-grid"), true);
assert.equal(stylesCss.includes(".roster-teamsheet"), true);
assert.equal(stylesCss.includes(".roster-teamsheet-grid"), true);
assert.equal(stylesCss.includes(".roster-teamsheet-row"), true);
assert.equal(stylesCss.includes(".roster-teamsheet-tile"), true);
assert.equal(stylesCss.includes(".roster-teamsheet-tile p"), false);
assert.equal(stylesCss.includes("--roster-bg-image"), true);
assert.equal(stylesCss.includes("background-size: cover;"), true);
assert.equal(stylesCss.includes("width: calc(100% - 20px);"), true);
assert.match(stylesCss, /\.pokemon-sprite-img\s*\{[\s\S]*?background: transparent;/);
assert.equal(stylesCss.includes(".person-summary-grid"), true);
assert.equal(stylesCss.includes("grid-template-columns: repeat(8, minmax(0, 1fr));"), true);
assert.equal(stylesCss.includes(".bracket-board"), true);
assert.equal(stylesCss.includes(".pokemon-sprite-animated"), true);
assert.equal(appJs.includes("setDetailSections("), true);
assert.equal(appJs.includes("renderBracketOverview("), true);
assert.equal(appJs.includes("renderRosterDetail("), true);
assert.equal(appJs.includes("rosterDetailLink("), true);
assert.equal(appJs.includes("rosterTeamSheet("), true);
assert.equal(appJs.includes("ROSTER_BACKGROUND_BY_SEASON"), true);
assert.equal(appJs.includes("gpl-s10-background.png"), true);
assert.equal(appJs.includes("rosterTeamSheetRows("), true);
assert.equal(appJs.includes("rosterTeamSheetTile("), true);
assert.equal(appJs.includes("rosterPokemonDisplayRows("), true);
assert.equal(appJs.includes("compareRosterPokemonBySlot("), true);
assert.equal(appJs.includes("rosterDisplaySlot("), true);
assert.equal(appJs.includes("tierLabel"), false);
assert.match(appJs, /<details class="roster-flags"><summary>/);
assert.match(appJs, /<details class="roster-detail-flags"><summary>/);
assert.equal(appJs.includes("rosterParticipantLink("), true);
assert.equal(appJs.includes('getPokemon?.(id, { gen: "ani" })'), true);
assert.equal(appJs.includes("pokemon-sprite-animated"), true);
assert.equal(appJs.includes("${fallback}<img"), false);
assert.equal(appJs.includes("renderTable(\"#battle-history-table\""), false);
assert.equal(appJs.includes('renderTable("#person-summary-table"'), false);
assert.equal(appJs.includes('renderTable("#pokemon-summary-table"'), false);
assert.equal(appJs.includes('navigateToView("all-time")'), true);
assert.match(appJs, /data-clear-person-focus[\s\S]*?navigateToView\("all-time"\)/);
assert.match(appJs, /data-clear-pokemon-focus[\s\S]*?navigateToView\("all-time"\)/);
assert.equal(appJs.includes("data-matchup-select"), true);
assert.equal(appJs.includes("selectMatchupParticipant("), true);
assert.match(appJs, /matchup:\s*\["matchVideos", "matchupSummary"\]/);
assert.match(appJs, /const matchColumns = columnsForProfile\(\["season", "division", "week", "player_a", "player_b", "score", "winner", "videos", "source"\]/);
assert.match(appJs, /videos:\s*videoLinksForMatch\(row\.match_id\)/);
assert.match(appJs, /tableHtml\(matchRows, matchColumns, \["player_a", "player_b", "videos", "source"\]\)/);
assert.equal(appJs.includes("personOptionsFromAllTimeRows("), true);
const matchupOptionsBlock = appJs.match(/function matchupOptions\(\) \{[\s\S]*?\n\}/)?.[0] ?? "";
assert.match(matchupOptionsBlock, /filteredPersonStats/);
assert.equal(matchupOptionsBlock.includes("team_a"), false);
assert.equal(matchupOptionsBlock.includes("team_name"), false);
assert.match(appJs, /seasonFilter\.addEventListener\("change"[\s\S]*?populateMatchupOptions\(\)/);
assert.match(appJs, /divisionFilter\.addEventListener\("change"[\s\S]*?populateMatchupOptions\(\)/);
assert.match(appJs, /searchFilter\.addEventListener\("input"[\s\S]*?populateMatchupOptions\(\)/);
assert.equal(dataModeSelect.includes('value="primary"'), true);
assert.equal(dataModeSelect.includes('value="all"'), true);
assert.equal(dataModeSelect.includes('value="league2"'), true);
assert.equal(dataModeSelect.includes('value="league1"'), false);
assert.match(appJs, /normalizeDataMode\(value\)[\s\S]*?value === "league2" \|\| value === "all"/);
assert.match(appJs, /state\.dataMode === "all"[\s\S]*?return true/);
assert.match(appJs, /function aggregateAllTimeRows\(\)[\s\S]*?state\.season !== "all"[\s\S]*?return null/);
assert.equal(columnProfileSelect.includes('value="compact"'), true);
assert.equal(columnProfileSelect.includes('value="performance"'), true);
assert.equal(columnProfileSelect.includes('value="history"'), true);
assert.equal(columnProfileSelect.includes('value="sources"'), true);
assert.equal(columnProfileSelect.includes('value="full"'), true);
assert.equal(appJs.includes('readPreference("gpl-column-profile", "full")'), true);
assert.equal(appJs.includes("applyDataMode("), true);
assert.equal(appJs.includes("columnsForProfile("), true);
assert.equal(appJs.includes("Top-11-Tiefe"), true);
assert.equal(appJs.includes("Tier-Streuung"), false);
assert.equal(appJs.includes("formatFormulaPercent("), true);
assert.equal(appJs.includes('join(" Â· ")'), false);
assert.equal(appJs.includes('join(" · ")'), true);
assert.equal(appJs.includes('matches: "KÃ¤mpfe"'), false);
assert.equal(appJs.includes('pokemonDraftOverview: "PokÃ©mon-Drafts"'), false);
assert.equal(appJs.includes('teamPokemonUsage: "Team-PokÃ©mon-Zuordnungen"'), false);
assert.equal(appJs.includes('missingKilllistAppearances: "Offene EinsÃ¤tze"'), false);
assert.equal(appJs.includes("Qualitt"), false);
assert.equal(appJs.includes("Prioritten"), false);
assert.match(appJs, /numberValue\(b\.rating\)[\s\S]*?numberValue\(b\.elo\)/);
